services:
  node_sqlite:
    build:
      context: node_sqlite/
      dockerfile: Dockerfile
    container_name: node_sqlite
    environment:
      - NODE_ENV=developmen
      # - NODE_ENV=production
    volumes:
      - fp_data:/var/fp_data/
      - sqlite_data:/var/sqlite_data/
    # restart: always
    expose:
      - "8081"
      - "22"
      - "12800"
    ports:
      - "2201:22"
      - "8001:8001"
      - "12800:12800"
    # user: "node"
    working_dir: /var/fp_data/
    command: "/home/node/run.sh"
    networks:
      - front-tier

  nginx_modsecurity:
    build:
      context: nginx_modsecurity/
      dockerfile: Dockerfile
    container_name: nginx_modsecurity
    ports:
      - "8443:8443"
      - "8080:8080"
    depends_on:
      - node_sqlite
    networks:
      - front-tier
    # volumes:
    #   - ms_log:/var/log/modsec
    environment:
      BACKEND: https://node_sqlite:12800
      PORT: 8080
      SSL_PORT: 8443
      SERVER_NAME: localhost
      SERVER_TOKENS: off
      NGINX_ALWAYS_TLS_REDIRECT: on
      SSL_CERT: /etc/nginx/ssl/front.crt
      SSL_CERT_KEY: /etc/nginx/ssl/front.key
      SSL_PROTOCOLS: "TLSv1.2 TLSv1.3"
      SSL_CIPHERS: "HIGH:!aNULL:!MD5"
      SSL_PREFER_CIPHERS: on
      SSL_VERIFY: off
      SSL_VERIFY_DEPTH: 1
      # PROXY_PASS: https://node_sqlite:12800
      PROXY_SSL_PROTOCOLS: "TLSv1.2 TLSv1.3"
      PROXY_SSL_CIPHERS: "HIGH:!aNULL:!MD5"
      PROXY_SSL_VERIFY: off
      MODSEC_AUDIT_ENGINE: on
      MODSEC_AUDIT_LOG: /var/log/modsec/audit.log
      LOGLEVEL: warn
      ERRORLOG: /var/log/modsec/error.log
      MODSECURITY_CONFIG: /opt/conf/modsecurity.conf
      CRS_SETUP_CONF: /opt/conf/crs-setup.conf

  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - front-tier

volumes:
  fp_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/GitHub/Pong
  sqlite_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/GitHub/Pong/data/sqlite
  ms_log:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/GitHub/Pong/docker/node_sqlite/log

networks:
  front-tier: {}
  back-tier: {}
